INSERT INTO users (email, password_hash) VALUES
('user1@example.com', 'hash1'),
('user2@example.com', 'hash2'),
('user3@example.com', 'hash3'),
('user4@example.com', 'hash4'),
('user5@example.com', 'hash5'),
('user6@example.com', 'hash6'),
('user7@example.com', 'hash7'),
('user8@example.com', 'hash8'),
('user9@example.com', 'hash9'),
('user10@example.com', 'hash10'),
('user11@example.com', 'hash11'),
('user12@example.com', 'hash12'),
('user13@example.com', 'hash13'),
('user14@example.com', 'hash14'),
('user15@example.com', 'hash15'),
('user16@example.com', 'hash16'),
('user17@example.com', 'hash17'),
('user18@example.com', 'hash18'),
('user19@example.com', 'hash19'),
('user20@example.com', 'hash20'),
('user21@example.com', 'hash21'),
('user22@example.com', 'hash22'),
('user23@example.com', 'hash23'),
('user24@example.com', 'hash24'),
('user25@example.com', 'hash25'),
('user26@example.com', 'hash26'),
('user27@example.com', 'hash27'),
('user28@example.com', 'hash28'),
('user29@example.com', 'hash29'),
('user30@example.com', 'hash30');

INSERT INTO profiles (user_id, username, first_name, last_name, bio) VALUES
(1, 'ali_k', 'Ali', 'Karimov', 'Backend developer.'),
(2, 'dilnoza_t', 'Dilnoza', 'Toshpulatova', 'Designer and artist.'),
(3, 'javlon_r', 'Javlon', 'Rahimov', 'Data analyst.'),
(4, 'malika_s', 'Malika', 'Sodiqova', 'Mobile developer.'),
(5, 'sherzod_a', 'Sherzod', 'Abdullayev', 'DevOps engineer.'),
(6, 'umida_x', 'Umida', 'Xolmatova', 'Student of computer science.'),
(7, 'aziz_q', 'Azizbek', 'Qodirov', 'Software engineer.'),
(8, 'shahnoza_i', 'Shahnoza', 'Ismoilova', 'Frontend developer.'),
(9, 'bekzod_s', 'Bekzod', 'Sobirov', 'Cybersecurity enthusiast.'),
(10, 'nodira_j', 'Nodira', 'Jo‘rayeva', 'Marketing specialist.'),
(11, 'oybek_r', 'Oybek', 'Rustamov', 'Cloud architect.'),
(12, 'sevinch_o', 'Sevinch', 'Ortiqova', 'UI/UX designer.'),
(13, 'jasur_y', 'Jasur', 'Yusupov', 'Blockchain developer.'),
(14, 'maftuna_e', 'Maftuna', 'Ergasheva', 'Business analyst.'),
(15, 'bobur_s', 'Bobur', 'Soliyev', 'Game developer.'),
(16, 'dildora_t', 'Dildora', 'Tursunova', 'QA engineer.'),
(17, 'iskandar_s', 'Iskandar', 'Sattorov', 'Database administrator.'),
(18, 'lobar_a', 'Lobar', 'Abdurahmonova', 'Project manager.'),
(19, 'murod_q', 'Murod', 'Qurbonov', 'AI researcher.'),
(20, 'gulbahor_h', 'Gulbahor', 'Hamroyeva', 'Fullstack developer.'),
(21, 'zafar_m', 'Zafar', 'Mamatov', 'Technical writer.'),
(22, 'shaxzod_n', 'Shaxzod', 'Nazarov', 'DevOps trainee.'),
(23, 'diyor_j', 'Diyorbek', 'Jumanov', 'Python backend developer.');

